{
 "title": "Пользовательская статистика",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Длительность сессии пользователя",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "firstT = from(bucket: \"example\")\n  |> range(start: time(v: 0))\n  |> filter(fn: (r) => r._measurement == \"user-clicks\")\n  |> group(columns: [\"sessionId\"])\n  |> first()\n\nlastT = from(bucket: \"example\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user-clicks\")\n  |> group(columns: [\"sessionId\"])\n  |> last()\n\njoin(\n    tables: {first: firstT, last: lastT },\n    on: [\"sessionId\"]\n  )\n  |> group()\n  |> map(fn: (r) => {\n    diff = uint(v: r._time_last) - uint(v: r._time_first)\n    return {\n      sessionId: r.sessionId, \n      first: r._time_first,\n      last: r._time_last,\n      diff: string(v: duration(v: diff)),\n      _diff: diff\n    }\n  })\n  |> sort(columns: [\"_diff\"], desc: true)"
    }
   ]
  },
  {
   "title": "Размер корзины пользователей",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"example\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user-clicks\")\n  |> filter(fn: (r) => contains(value: r[\"event\"], set: [\"addBasket\", \"loadBasket\", \"delBasket\"]))\n  |> group(columns: [\"sessionId\"])\n  |> last()\n  |> group()\n  |> map(fn: (r) => ({r with size: length(arr: strings.split(t: \",\", v: r.basket))}))\n  |> keep(columns: [\"sessionId\", \"size\"])"
    }
   ]
  },
  {
   "title": "Всего пользователей",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"example\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user-clicks\")\n  |> filter(fn: (r) => r[\"event\"] == \"pageview\")\n  |> group(columns: [\"sessionId\"])\n  |> distinct(column: \"sessionId\")\n  |> group()\n  |> count()\n  |> group()\n  |> yield(name: \"users\")"
    }
   ]
  }
 ]
}